{% set name = "EODIE" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/eetun-tiimi/EODIE/-/archive/v7_test/EODIE-v7_test.tar.gz
  #url: https://gitlab.com/eetun-tiimi/EODIE/-/archive/v{{ version }}/EODIE-v{{ version }}.tar.gz
  #sha256: 6d7dd064152a8a41a310006f7b7f3e5e0c6b26b14fcee636962c4a97dbd80813

build:
  skip: true # [win]
  number: 0
  #script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - shapely
    - rasterio
    - rasterstats
    - fiona
    - numpy
    - gdal
    - pyyaml
    - pytest
    - matplotlib
  run:
    - python >=3.6
    - shapely
    - rasterio
    - rasterstats
    - fiona
    - numpy
    - gdal
    - pyyaml
    - pytest
    - matplotlib

test:
  imports: 
    - eodie   
  commands:
    - eodie_process.py --help


about:
  home: https://gitlab.com/eetun-tiimi/EODIE
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Earth Observation Data Information Extractor

  description: Earth Observation Data Information Extractor
  doc_url: https://eodie.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/eetun-tiimi/EODIE

extra:
  recipe-maintainers:
    - samumantha

